### ISSUE TITLE
Remove project databases from extensions.

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#357]
Once we've moved the extensions to https://github.com/eclipse/jnosql-databases

It is time to remove those databases behaviors from the [extensions](https://github.com/eclipse/jnosql-extensions)

## Task

- [x] Remove those modules from the source code:
   -  jnosql-arangodb-extension
   -  jnosql-cassandra-extension
   -  jnosql-couchbase-extension
   -  jnosql-elasticsearch-extension
   -  jnosql-hazelcast-extension
   -  jnosql-mongodb-extension
   -  jnosql-orientdb-extension
   -  jnosql-solr-extension

- [x] Update the README to remove any references around those databases
- [x] Add on Change-log those items as removed
