### ISSUE TITLE
Move jnosql-validations project to extensions

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#358]
Ref: https://github.com/eclipse/jnosql/issues/353

With the new extensions home, it is time to move [jnosql-validation](https://github.com/eclipse/jnosql/tree/main/jnosql-mapping/jnosql-mapping-validation) to the [extensions](https://github.com/eclipse/jnosql-extensions) repository.

## Tasks

- [x] Move the project to extensions
- [x] Remove the project from Eclipse JNoSQL
- [x] Update both change logs with the change
- [ ] Move the read-me of validation to the new place.

**Comment by dminkovski** [comment]
@otaviojava I would like to try this if you don't mind.
