### ISSUE TITLE
Enhance contributing file with git commit details

### ISSUE THREAD

**Issue by otaviojava** [eclipse/jnosql#361]
## Description

As a contributor to the Eclipse JNoSQL project, I want clear instructions on making git commits by the Conventional Commits specification (https://www.conventionalcommits.org/en/v1.0.0/), so that my commits are consistent and easy to understand.

## Proposed Solution
Add a section to the CONTRIBUTING.md file that explains the Conventional Commits specification and how to use it in the project. This should include instructions on how to format commit messages and which types of messages to use for different kinds of changes.

## Acceptance Criteria

- The CONTRIBUTING.md file includes a new section on git commit details
- The new section explains the Conventional Commits specification and how to use it in the project
- The new section includes instructions on how to format commit messages and which types of messages to use for different types of changes

## Task

- [ ] Update the Contributing file on Eclipse JNoSQL
 - [ ] Update the Contributing file on Eclipse Database
- [ ] Update the Contributing file on Eclipse Extensions

:information_source: you can use the https://www.conventionalcommits.org/en/v1.0.0/ as a good reference documentation.

**Comment by scorcism** [comment]
Hello @otaviojava I would like work on this. Can you assign me.
From my understaning I have to create a section and in there just have to mention steps for conventionalcommits.

**Comment by nitin1chandani** [comment]
I want to work on this, can you assign me.

**Comment by otaviojava** [comment]
There is a work on this issue:
https://github.com/eclipse/jnosql/pull/363
